### PR TITLE
consul-lb can't health check itself when USE_SSL='0'

### PR DESCRIPTION
**Pull request by larslevie**

### CODE REVIEW

**Comment by caseywebdev** [comment]
Good catch. It seems like we'd only need the `302` redirect when going from HTTP -> HTTPS though because any matching `server_name`s will hit those server blocks before the `default_server` block, so how about...

```nginx
location / {
{{- if eq (env "USE_SSL") "1" }}
  return 302 https://$host$request_uri;
{{- else}}
  return 204;
{{- end}}
}
```

**Comment by larslevie** [comment]
Good point that we don't need to upgrade the request with a redirect when not using SSL, but if we are never hitting the `default_server` block, then why is the `return 204` necessary at all (it is, without it, requests are served consul-lab's "Welcome to nginx" page)?

**Comment by caseywebdev** [comment]
The `default_server` block is hit for any http request that doesn't match another block's `server_name`, which would include the health check since it's `http://localhost`.

**Comment by larslevie** [comment]
4pmx5rj4pyaem

**Comment by caseywebdev** [comment]
Muchos gracias señor!

**Pull request merged**
